name: Lewicki's Blog
description: Things I think are interesting or useful.
meta_description: "Lewicki's Blog, things they think are interesting or useful."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog
domain_name: "https://lewicki.dev"
plugins: [jekyll-paginate]